# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WindowGui.ui'
#
# Created: Tue Dec  9 21:40:06 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(849, 627)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setFocusPolicy(QtCore.Qt.TabFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../assets/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.portscanner = QtGui.QWidget()
        self.portscanner.setStyleSheet("")
        self.portscanner.setObjectName("portscanner")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.portscanner)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtGui.QFrame(self.portscanner)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtGui.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.portscannerstart = QtGui.QPushButton(self.frame)
        self.portscannerstart.setObjectName("portscannerstart")
        self.gridLayout_2.addWidget(self.portscannerstart, 0, 2, 1, 1)
        self.portscannerport = QtGui.QLineEdit(self.frame)
        self.portscannerport.setObjectName("portscannerport")
        self.gridLayout_2.addWidget(self.portscannerport, 0, 1, 1, 1)
        self.portscannerip = QtGui.QLineEdit(self.frame)
        self.portscannerip.setObjectName("portscannerip")
        self.gridLayout_2.addWidget(self.portscannerip, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.frame)
        self.portscannerconsole = QtGui.QTextBrowser(self.portscanner)
        self.portscannerconsole.setAutoFillBackground(True)
        self.portscannerconsole.setStyleSheet("")
        self.portscannerconsole.setFrameShape(QtGui.QFrame.StyledPanel)
        self.portscannerconsole.setFrameShadow(QtGui.QFrame.Sunken)
        self.portscannerconsole.setTabChangesFocus(False)
        self.portscannerconsole.setUndoRedoEnabled(False)
        self.portscannerconsole.setReadOnly(True)
        self.portscannerconsole.setAcceptRichText(True)
        self.portscannerconsole.setObjectName("portscannerconsole")
        self.verticalLayout_3.addWidget(self.portscannerconsole)
        self.tabWidget.addTab(self.portscanner, "")
        self.serverscanner = QtGui.QWidget()
        self.serverscanner.setObjectName("serverscanner")
        self.gridLayout = QtGui.QGridLayout(self.serverscanner)
        self.gridLayout.setObjectName("gridLayout")
        self.serverscannerip = QtGui.QLineEdit(self.serverscanner)
        self.serverscannerip.setObjectName("serverscannerip")
        self.gridLayout.addWidget(self.serverscannerip, 0, 0, 1, 1)
        self.serverscannerport = QtGui.QLineEdit(self.serverscanner)
        self.serverscannerport.setObjectName("serverscannerport")
        self.gridLayout.addWidget(self.serverscannerport, 0, 1, 1, 1)
        self.serverscannerstart = QtGui.QPushButton(self.serverscanner)
        self.serverscannerstart.setObjectName("serverscannerstart")
        self.gridLayout.addWidget(self.serverscannerstart, 0, 2, 1, 1)
        self.serverscannerconsole = QtGui.QTextBrowser(self.serverscanner)
        self.serverscannerconsole.setAutoFillBackground(True)
        self.serverscannerconsole.setStyleSheet("")
        self.serverscannerconsole.setFrameShape(QtGui.QFrame.StyledPanel)
        self.serverscannerconsole.setFrameShadow(QtGui.QFrame.Sunken)
        self.serverscannerconsole.setTabChangesFocus(False)
        self.serverscannerconsole.setUndoRedoEnabled(False)
        self.serverscannerconsole.setReadOnly(True)
        self.serverscannerconsole.setAcceptRichText(True)
        self.serverscannerconsole.setObjectName("serverscannerconsole")
        self.gridLayout.addWidget(self.serverscannerconsole, 1, 0, 1, 3)
        self.tabWidget.addTab(self.serverscanner, "")
        self.spider = QtGui.QWidget()
        self.spider.setObjectName("spider")
        self.tabWidget.addTab(self.spider, "")
        self.bruteforcer = QtGui.QWidget()
        self.bruteforcer.setObjectName("bruteforcer")
        self.tabWidget.addTab(self.bruteforcer, "")
        self.repeater = QtGui.QWidget()
        self.repeater.setObjectName("repeater")
        self.tabWidget.addTab(self.repeater, "")
        self.sqli = QtGui.QWidget()
        self.sqli.setObjectName("sqli")
        self.tabWidget.addTab(self.sqli, "")
        self.xss = QtGui.QWidget()
        self.xss.setObjectName("xss")
        self.tabWidget.addTab(self.xss, "")
        self.onlinebot = QtGui.QWidget()
        self.onlinebot.setObjectName("onlinebot")
        self.tabWidget.addTab(self.onlinebot, "")
        self.encoder = QtGui.QWidget()
        self.encoder.setObjectName("encoder")
        self.tabWidget.addTab(self.encoder, "")
        self.browser = QtGui.QWidget()
        self.browser.setObjectName("browser")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.browser)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.browserlocationbarframe = QtGui.QFrame(self.browser)
        self.browserlocationbarframe.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.browserlocationbarframe.setFrameShape(QtGui.QFrame.StyledPanel)
        self.browserlocationbarframe.setFrameShadow(QtGui.QFrame.Raised)
        self.browserlocationbarframe.setObjectName("browserlocationbarframe")
        self.horizontalLayout = QtGui.QHBoxLayout(self.browserlocationbarframe)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.browsergoback = QtGui.QToolButton(self.browserlocationbarframe)
        self.browsergoback.setStyleSheet("border:0;\n"
"\n"
"\n"
"background-color: rgb(204, 204, 204);")
        self.browsergoback.setObjectName("browsergoback")
        self.horizontalLayout.addWidget(self.browsergoback)
        self.browsergogront = QtGui.QToolButton(self.browserlocationbarframe)
        self.browsergogront.setStyleSheet("border:0;\n"
"\n"
"\n"
"background-color: rgb(204, 204, 204);")
        self.browsergogront.setObjectName("browsergogront")
        self.horizontalLayout.addWidget(self.browsergogront)
        self.browseraddress = QtGui.QLineEdit(self.browserlocationbarframe)
        self.browseraddress.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.browseraddress.setObjectName("browseraddress")
        self.horizontalLayout.addWidget(self.browseraddress)
        self.browserreload = QtGui.QToolButton(self.browserlocationbarframe)
        self.browserreload.setStyleSheet("border:0;\n"
"\n"
"\n"
"background-color: rgb(204, 204, 204);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("assets/reload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.browserreload.setIcon(icon1)
        self.browserreload.setObjectName("browserreload")
        self.horizontalLayout.addWidget(self.browserreload)
        self.verticalLayout_4.addWidget(self.browserlocationbarframe)
        self.browserbodylayout = QtGui.QHBoxLayout()
        self.browserbodylayout.setObjectName("browserbodylayout")
        self.verticalLayout_4.addLayout(self.browserbodylayout)
        self.tabWidget.addTab(self.browser, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 849, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setStatusTip("")
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtGui.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionExit_2 = QtGui.QAction(MainWindow)
        self.actionExit_2.setObjectName("actionExit_2")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit_2)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(9)
        QtCore.QObject.connect(self.actionExit_2, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.portscanner.setStatusTip(QtGui.QApplication.translate("MainWindow", "Scans for the open ports of the web server", None, QtGui.QApplication.UnicodeUTF8))
        self.portscanner.setAccessibleName(QtGui.QApplication.translate("MainWindow", "Scanner", None, QtGui.QApplication.UnicodeUTF8))
        self.portscannerstart.setStatusTip(QtGui.QApplication.translate("MainWindow", "Start!", None, QtGui.QApplication.UnicodeUTF8))
        self.portscannerstart.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.portscannerport.setStatusTip(QtGui.QApplication.translate("MainWindow", "Enter port range Ex: 80,1-65535,80-443", None, QtGui.QApplication.UnicodeUTF8))
        self.portscannerport.setText(QtGui.QApplication.translate("MainWindow", "80", None, QtGui.QApplication.UnicodeUTF8))
        self.portscannerport.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "  Port", None, QtGui.QApplication.UnicodeUTF8))
        self.portscannerip.setStatusTip(QtGui.QApplication.translate("MainWindow", "IP Address or the host name of the web server", None, QtGui.QApplication.UnicodeUTF8))
        self.portscannerip.setText(QtGui.QApplication.translate("MainWindow", "127.0.0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.portscannerip.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Server IP Address", None, QtGui.QApplication.UnicodeUTF8))
        self.portscannerconsole.setStatusTip(QtGui.QApplication.translate("MainWindow", "Port Scanner Log", None, QtGui.QApplication.UnicodeUTF8))
        self.portscannerconsole.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.portscanner), QtGui.QApplication.translate("MainWindow", "Port Scanner", None, QtGui.QApplication.UnicodeUTF8))
        self.serverscanner.setStatusTip(QtGui.QApplication.translate("MainWindow", "Scans the web server for the known server side vulnerabilities using nikto exploit database", None, QtGui.QApplication.UnicodeUTF8))
        self.serverscannerip.setStatusTip(QtGui.QApplication.translate("MainWindow", "IP Address or the host name of the web server", None, QtGui.QApplication.UnicodeUTF8))
        self.serverscannerip.setText(QtGui.QApplication.translate("MainWindow", "127.0.0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.serverscannerip.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Server IP Address", None, QtGui.QApplication.UnicodeUTF8))
        self.serverscannerport.setStatusTip(QtGui.QApplication.translate("MainWindow", "Port number of the target web server", None, QtGui.QApplication.UnicodeUTF8))
        self.serverscannerport.setText(QtGui.QApplication.translate("MainWindow", "80", None, QtGui.QApplication.UnicodeUTF8))
        self.serverscannerport.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "  Port", None, QtGui.QApplication.UnicodeUTF8))
        self.serverscannerstart.setStatusTip(QtGui.QApplication.translate("MainWindow", "Start!", None, QtGui.QApplication.UnicodeUTF8))
        self.serverscannerstart.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.serverscannerconsole.setStatusTip(QtGui.QApplication.translate("MainWindow", "Server Scanner Log", None, QtGui.QApplication.UnicodeUTF8))
        self.serverscannerconsole.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.serverscanner), QtGui.QApplication.translate("MainWindow", "Server Scanner", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.spider), QtGui.QApplication.translate("MainWindow", "Spider", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.bruteforcer), QtGui.QApplication.translate("MainWindow", "Bruteforcer", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.repeater), QtGui.QApplication.translate("MainWindow", "Repeater", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sqli), QtGui.QApplication.translate("MainWindow", "SQLi", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.xss), QtGui.QApplication.translate("MainWindow", "XSS", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.onlinebot), QtGui.QApplication.translate("MainWindow", "Online Exploits", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.encoder), QtGui.QApplication.translate("MainWindow", "En(De)coder", None, QtGui.QApplication.UnicodeUTF8))
        self.browsergoback.setText(QtGui.QApplication.translate("MainWindow", "<-", None, QtGui.QApplication.UnicodeUTF8))
        self.browsergogront.setText(QtGui.QApplication.translate("MainWindow", "->", None, QtGui.QApplication.UnicodeUTF8))
        self.browseraddress.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Enter Address", None, QtGui.QApplication.UnicodeUTF8))
        self.browserreload.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.browser), QtGui.QApplication.translate("MainWindow", "Browser", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setStatusTip(QtGui.QApplication.translate("MainWindow", "About project", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+L", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setText(QtGui.QApplication.translate("MainWindow", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit_2.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))

