# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WindowGui.ui'
#
# Created: Tue May  5 10:38:19 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(843, 608)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setFocusPolicy(QtCore.Qt.TabFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.portscanner = QtGui.QWidget()
        self.portscanner.setStyleSheet("")
        self.portscanner.setObjectName("portscanner")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.portscanner)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtGui.QFrame(self.portscanner)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtGui.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.portscannerip = QtGui.QLineEdit(self.frame)
        self.portscannerip.setObjectName("portscannerip")
        self.gridLayout_2.addWidget(self.portscannerip, 0, 0, 1, 1)
        self.portscannerport = QtGui.QLineEdit(self.frame)
        self.portscannerport.setMaximumSize(QtCore.QSize(130, 16777215))
        self.portscannerport.setObjectName("portscannerport")
        self.gridLayout_2.addWidget(self.portscannerport, 0, 1, 1, 1)
        self.portscannerstart = QtGui.QPushButton(self.frame)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../.designer/assets/index.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.portscannerstart.setIcon(icon1)
        self.portscannerstart.setObjectName("portscannerstart")
        self.gridLayout_2.addWidget(self.portscannerstart, 0, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.frame)
        self.portscannerconsole = QtGui.QTextBrowser(self.portscanner)
        self.portscannerconsole.setAutoFillBackground(True)
        self.portscannerconsole.setStyleSheet("")
        self.portscannerconsole.setFrameShape(QtGui.QFrame.StyledPanel)
        self.portscannerconsole.setFrameShadow(QtGui.QFrame.Sunken)
        self.portscannerconsole.setTabChangesFocus(False)
        self.portscannerconsole.setUndoRedoEnabled(False)
        self.portscannerconsole.setReadOnly(True)
        self.portscannerconsole.setAcceptRichText(True)
        self.portscannerconsole.setObjectName("portscannerconsole")
        self.verticalLayout_3.addWidget(self.portscannerconsole)
        self.tabWidget.addTab(self.portscanner, "")
        self.serverscanner = QtGui.QWidget()
        self.serverscanner.setObjectName("serverscanner")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.serverscanner)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_3 = QtGui.QFrame(self.serverscanner)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.serverscannerip = QtGui.QLineEdit(self.frame_3)
        self.serverscannerip.setObjectName("serverscannerip")
        self.horizontalLayout_4.addWidget(self.serverscannerip)
        self.serverscannerport = QtGui.QLineEdit(self.frame_3)
        self.serverscannerport.setMaximumSize(QtCore.QSize(130, 16777215))
        self.serverscannerport.setObjectName("serverscannerport")
        self.horizontalLayout_4.addWidget(self.serverscannerport)
        self.serverscannerstart = QtGui.QPushButton(self.frame_3)
        self.serverscannerstart.setIcon(icon1)
        self.serverscannerstart.setObjectName("serverscannerstart")
        self.horizontalLayout_4.addWidget(self.serverscannerstart)
        self.verticalLayout_4.addWidget(self.frame_3)
        self.serverscannerconsole = QtGui.QTextBrowser(self.serverscanner)
        self.serverscannerconsole.setAutoFillBackground(True)
        self.serverscannerconsole.setStyleSheet("")
        self.serverscannerconsole.setFrameShape(QtGui.QFrame.StyledPanel)
        self.serverscannerconsole.setFrameShadow(QtGui.QFrame.Sunken)
        self.serverscannerconsole.setTabChangesFocus(False)
        self.serverscannerconsole.setUndoRedoEnabled(False)
        self.serverscannerconsole.setReadOnly(True)
        self.serverscannerconsole.setAcceptRichText(True)
        self.serverscannerconsole.setObjectName("serverscannerconsole")
        self.verticalLayout_4.addWidget(self.serverscannerconsole)
        self.tabWidget.addTab(self.serverscanner, "")
        self.spider = QtGui.QWidget()
        self.spider.setObjectName("spider")
        self.gridLayout_6 = QtGui.QGridLayout(self.spider)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_6.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.spider, "")
        self.bruteforcer = QtGui.QWidget()
        self.bruteforcer.setObjectName("bruteforcer")
        self.tabWidget.addTab(self.bruteforcer, "")
        self.repeater = QtGui.QWidget()
        self.repeater.setObjectName("repeater")
        self.gridLayout_5 = QtGui.QGridLayout(self.repeater)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.repeaterheaderbody = QtGui.QTextEdit(self.repeater)
        self.repeaterheaderbody.setStyleSheet("")
        self.repeaterheaderbody.setObjectName("repeaterheaderbody")
        self.gridLayout_4.addWidget(self.repeaterheaderbody, 1, 0, 1, 2)
        self.repeaterurledit = QtGui.QLineEdit(self.repeater)
        self.repeaterurledit.setObjectName("repeaterurledit")
        self.gridLayout_4.addWidget(self.repeaterurledit, 0, 0, 1, 1)
        self.repeatersend = QtGui.QPushButton(self.repeater)
        self.repeatersend.setObjectName("repeatersend")
        self.gridLayout_4.addWidget(self.repeatersend, 0, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.repeatertabs = QtGui.QTabWidget(self.repeater)
        self.repeatertabs.setTabPosition(QtGui.QTabWidget.North)
        self.repeatertabs.setTabShape(QtGui.QTabWidget.Rounded)
        self.repeatertabs.setElideMode(QtCore.Qt.ElideNone)
        self.repeatertabs.setDocumentMode(False)
        self.repeatertabs.setTabsClosable(False)
        self.repeatertabs.setMovable(True)
        self.repeatertabs.setObjectName("repeatertabs")
        self.repeaterreq = QtGui.QWidget()
        self.repeaterreq.setObjectName("repeaterreq")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.repeaterreq)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.repeaterreqlayout = QtGui.QVBoxLayout()
        self.repeaterreqlayout.setObjectName("repeaterreqlayout")
        self.repeaterresponcereq = QtGui.QTextBrowser(self.repeaterreq)
        self.repeaterresponcereq.setObjectName("repeaterresponcereq")
        self.repeaterreqlayout.addWidget(self.repeaterresponcereq)
        self.verticalLayout_10.addLayout(self.repeaterreqlayout)
        self.repeatertabs.addTab(self.repeaterreq, "")
        self.repeaterres = QtGui.QWidget()
        self.repeaterres.setObjectName("repeaterres")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.repeaterres)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.repeaterreslayout = QtGui.QVBoxLayout()
        self.repeaterreslayout.setObjectName("repeaterreslayout")
        self.repeaterresponceres = QtGui.QTextBrowser(self.repeaterres)
        self.repeaterresponceres.setObjectName("repeaterresponceres")
        self.repeaterreslayout.addWidget(self.repeaterresponceres)
        self.verticalLayout_8.addLayout(self.repeaterreslayout)
        self.repeatertabs.addTab(self.repeaterres, "")
        self.repeatercookies = QtGui.QWidget()
        self.repeatercookies.setObjectName("repeatercookies")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.repeatercookies)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.repeaterresponcecookies = QtGui.QTextBrowser(self.repeatercookies)
        self.repeaterresponcecookies.setObjectName("repeaterresponcecookies")
        self.verticalLayout_7.addWidget(self.repeaterresponcecookies)
        self.verticalLayout_9.addLayout(self.verticalLayout_7)
        self.repeatertabs.addTab(self.repeatercookies, "")
        self.repeaterview = QtGui.QWidget()
        self.repeaterview.setObjectName("repeaterview")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.repeaterview)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.repeaterresponceview = QtGui.QTextBrowser(self.repeaterview)
        self.repeaterresponceview.setObjectName("repeaterresponceview")
        self.verticalLayout_11.addWidget(self.repeaterresponceview)
        self.verticalLayout_12.addLayout(self.verticalLayout_11)
        self.repeatertabs.addTab(self.repeaterview, "")
        self.gridLayout_5.addWidget(self.repeatertabs, 1, 0, 1, 1)
        self.tabWidget.addTab(self.repeater, "")
        self.sqli = QtGui.QWidget()
        self.sqli.setObjectName("sqli")
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.sqli)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.sqlilayoyt = QtGui.QVBoxLayout()
        self.sqlilayoyt.setObjectName("sqlilayoyt")
        self.frame_4 = QtGui.QFrame(self.sqli)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.frame_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.sqliedit = QtGui.QLineEdit(self.frame_4)
        self.sqliedit.setObjectName("sqliedit")
        self.horizontalLayout_5.addWidget(self.sqliedit)
        self.sqlistart = QtGui.QPushButton(self.frame_4)
        self.sqlistart.setObjectName("sqlistart")
        self.horizontalLayout_5.addWidget(self.sqlistart)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_5.addLayout(self.horizontalLayout_3)
        self.sqlilayoyt.addWidget(self.frame_4)
        self.verticalLayout_14.addLayout(self.sqlilayoyt)
        self.sqlitb = QtGui.QTextBrowser(self.sqli)
        self.sqlitb.setObjectName("sqlitb")
        self.verticalLayout_14.addWidget(self.sqlitb)
        self.tabWidget.addTab(self.sqli, "")
        self.xss = QtGui.QWidget()
        self.xss.setObjectName("xss")
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.xss)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.frame_6 = QtGui.QFrame(self.xss)
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.frame_6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lineEdit = QtGui.QLineEdit(self.frame_6)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_9.addWidget(self.lineEdit)
        self.pushButton = QtGui.QPushButton(self.frame_6)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_9.addWidget(self.pushButton)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_9.addLayout(self.horizontalLayout_8)
        self.verticalLayout_16.addWidget(self.frame_6)
        self.verticalLayout_17.addLayout(self.verticalLayout_16)
        self.textBrowser = QtGui.QTextBrowser(self.xss)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_17.addWidget(self.textBrowser)
        self.tabWidget.addTab(self.xss, "")
        self.onlinebot = QtGui.QWidget()
        self.onlinebot.setObjectName("onlinebot")
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.onlinebot)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_5 = QtGui.QFrame(self.onlinebot)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.frame_5)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.expedit = QtGui.QLineEdit(self.frame_5)
        self.expedit.setObjectName("expedit")
        self.horizontalLayout_7.addWidget(self.expedit)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.expstart = QtGui.QPushButton(self.frame_5)
        self.expstart.setObjectName("expstart")
        self.horizontalLayout_7.addWidget(self.expstart)
        self.verticalLayout_13.addWidget(self.frame_5)
        self.verticalLayout_15.addLayout(self.verticalLayout_13)
        self.exptb = QtGui.QTextBrowser(self.onlinebot)
        self.exptb.setObjectName("exptb")
        self.verticalLayout_15.addWidget(self.exptb)
        self.tabWidget.addTab(self.onlinebot, "")
        self.encoder = QtGui.QWidget()
        self.encoder.setObjectName("encoder")
        self.gridLayout_3 = QtGui.QGridLayout(self.encoder)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.encoderstart = QtGui.QComboBox(self.encoder)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(86, 86, 86))
        gradient.setColorAt(0.1, QtGui.QColor(82, 82, 82))
        gradient.setColorAt(0.5, QtGui.QColor(78, 78, 78))
        gradient.setColorAt(0.9, QtGui.QColor(74, 74, 74))
        gradient.setColorAt(1.0, QtGui.QColor(70, 70, 70))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(86, 86, 86))
        gradient.setColorAt(0.1, QtGui.QColor(82, 82, 82))
        gradient.setColorAt(0.5, QtGui.QColor(78, 78, 78))
        gradient.setColorAt(0.9, QtGui.QColor(74, 74, 74))
        gradient.setColorAt(1.0, QtGui.QColor(70, 70, 70))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(86, 86, 86))
        gradient.setColorAt(0.1, QtGui.QColor(82, 82, 82))
        gradient.setColorAt(0.5, QtGui.QColor(78, 78, 78))
        gradient.setColorAt(0.9, QtGui.QColor(74, 74, 74))
        gradient.setColorAt(1.0, QtGui.QColor(70, 70, 70))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(172, 172, 172))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(86, 86, 86))
        gradient.setColorAt(0.1, QtGui.QColor(82, 82, 82))
        gradient.setColorAt(0.5, QtGui.QColor(78, 78, 78))
        gradient.setColorAt(0.9, QtGui.QColor(74, 74, 74))
        gradient.setColorAt(1.0, QtGui.QColor(70, 70, 70))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(86, 86, 86))
        gradient.setColorAt(0.1, QtGui.QColor(82, 82, 82))
        gradient.setColorAt(0.5, QtGui.QColor(78, 78, 78))
        gradient.setColorAt(0.9, QtGui.QColor(74, 74, 74))
        gradient.setColorAt(1.0, QtGui.QColor(70, 70, 70))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(86, 86, 86))
        gradient.setColorAt(0.1, QtGui.QColor(82, 82, 82))
        gradient.setColorAt(0.5, QtGui.QColor(78, 78, 78))
        gradient.setColorAt(0.9, QtGui.QColor(74, 74, 74))
        gradient.setColorAt(1.0, QtGui.QColor(70, 70, 70))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(172, 172, 172))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(64, 64, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(64, 64, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(64, 64, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(172, 172, 172))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.encoderstart.setPalette(palette)
        self.encoderstart.setObjectName("encoderstart")
        self.encoderstart.addItem("")
        self.encoderstart.addItem("")
        self.encoderstart.addItem("")
        self.encoderstart.addItem("")
        self.encoderstart.addItem("")
        self.encoderstart.addItem("")
        self.encoderstart.addItem("")
        self.encoderstart.addItem("")
        self.encoderstart.addItem("")
        self.gridLayout_3.addWidget(self.encoderstart, 0, 0, 1, 2)
        self.input = QtGui.QLabel(self.encoder)
        self.input.setObjectName("input")
        self.gridLayout_3.addWidget(self.input, 1, 0, 1, 1)
        self.encoderinput = QtGui.QTextEdit(self.encoder)
        self.encoderinput.setObjectName("encoderinput")
        self.gridLayout_3.addWidget(self.encoderinput, 1, 1, 1, 1)
        self.output = QtGui.QLabel(self.encoder)
        self.output.setObjectName("output")
        self.gridLayout_3.addWidget(self.output, 2, 0, 1, 1)
        self.encoderoutput = QtGui.QTextEdit(self.encoder)
        self.encoderoutput.setObjectName("encoderoutput")
        self.gridLayout_3.addWidget(self.encoderoutput, 2, 1, 1, 1)
        self.tabWidget.addTab(self.encoder, "")
        self.browser = QtGui.QWidget()
        self.browser.setObjectName("browser")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.browser)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.browserbodylayout = QtGui.QVBoxLayout()
        self.browserbodylayout.setObjectName("browserbodylayout")
        self.frame_2 = QtGui.QFrame(self.browser)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.browsergoback = QtGui.QToolButton(self.frame_2)
        self.browsergoback.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/bleft.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.browsergoback.setIcon(icon2)
        self.browsergoback.setObjectName("browsergoback")
        self.horizontalLayout.addWidget(self.browsergoback)
        self.browsergofront = QtGui.QToolButton(self.frame_2)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/bright.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.browsergofront.setIcon(icon3)
        self.browsergofront.setObjectName("browsergofront")
        self.horizontalLayout.addWidget(self.browsergofront)
        self.browserreload = QtGui.QToolButton(self.frame_2)
        self.browserreload.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/breload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.browserreload.setIcon(icon4)
        self.browserreload.setObjectName("browserreload")
        self.horizontalLayout.addWidget(self.browserreload)
        self.browseraddress = QtGui.QLineEdit(self.frame_2)
        self.browseraddress.setObjectName("browseraddress")
        self.horizontalLayout.addWidget(self.browseraddress)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.browserbodylayout.addWidget(self.frame_2)
        self.verticalLayout_5.addLayout(self.browserbodylayout)
        self.tabWidget.addTab(self.browser, "")
        self.shell = QtGui.QWidget()
        self.shell.setObjectName("shell")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.shell)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.shellstart = QtGui.QPushButton(self.shell)
        self.shellstart.setObjectName("shellstart")
        self.gridLayout_7.addWidget(self.shellstart, 0, 0, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_7)
        self.tabWidget.addTab(self.shell, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 843, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setStatusTip("")
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtGui.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionExit_2 = QtGui.QAction(MainWindow)
        self.actionExit_2.setObjectName("actionExit_2")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit_2)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(6)
        self.repeatertabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Hackstack", None, QtGui.QApplication.UnicodeUTF8))
        self.portscanner.setStatusTip(QtGui.QApplication.translate("MainWindow", "Scans for the open ports of the web server", None, QtGui.QApplication.UnicodeUTF8))
        self.portscanner.setAccessibleName(QtGui.QApplication.translate("MainWindow", "Scanner", None, QtGui.QApplication.UnicodeUTF8))
        self.portscannerip.setStatusTip(QtGui.QApplication.translate("MainWindow", "IP Address or the host name of the web server", None, QtGui.QApplication.UnicodeUTF8))
        self.portscannerip.setText(QtGui.QApplication.translate("MainWindow", "127.0.0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.portscannerip.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Server IP Address", None, QtGui.QApplication.UnicodeUTF8))
        self.portscannerport.setStatusTip(QtGui.QApplication.translate("MainWindow", "Enter port range Ex: 80,1-65535,80-443", None, QtGui.QApplication.UnicodeUTF8))
        self.portscannerport.setText(QtGui.QApplication.translate("MainWindow", "80", None, QtGui.QApplication.UnicodeUTF8))
        self.portscannerport.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "  Port", None, QtGui.QApplication.UnicodeUTF8))
        self.portscannerstart.setStatusTip(QtGui.QApplication.translate("MainWindow", "Start!", None, QtGui.QApplication.UnicodeUTF8))
        self.portscannerstart.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.portscannerconsole.setStatusTip(QtGui.QApplication.translate("MainWindow", "Port Scanner Log", None, QtGui.QApplication.UnicodeUTF8))
        self.portscannerconsole.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.portscanner), QtGui.QApplication.translate("MainWindow", "Port Scanner", None, QtGui.QApplication.UnicodeUTF8))
        self.serverscanner.setStatusTip(QtGui.QApplication.translate("MainWindow", "Scans the web server for the known server side vulnerabilities using nikto exploit database", None, QtGui.QApplication.UnicodeUTF8))
        self.serverscannerip.setStatusTip(QtGui.QApplication.translate("MainWindow", "IP Address or the host name of the web server", None, QtGui.QApplication.UnicodeUTF8))
        self.serverscannerip.setText(QtGui.QApplication.translate("MainWindow", "127.0.0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.serverscannerip.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Server IP Address", None, QtGui.QApplication.UnicodeUTF8))
        self.serverscannerport.setStatusTip(QtGui.QApplication.translate("MainWindow", "Port number of the target web server", None, QtGui.QApplication.UnicodeUTF8))
        self.serverscannerport.setText(QtGui.QApplication.translate("MainWindow", "80", None, QtGui.QApplication.UnicodeUTF8))
        self.serverscannerport.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "  Port", None, QtGui.QApplication.UnicodeUTF8))
        self.serverscannerstart.setStatusTip(QtGui.QApplication.translate("MainWindow", "Start!", None, QtGui.QApplication.UnicodeUTF8))
        self.serverscannerstart.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.serverscannerconsole.setStatusTip(QtGui.QApplication.translate("MainWindow", "Server Scanner Log", None, QtGui.QApplication.UnicodeUTF8))
        self.serverscannerconsole.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.serverscanner), QtGui.QApplication.translate("MainWindow", "Server Scanner", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.spider), QtGui.QApplication.translate("MainWindow", "Spider", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.bruteforcer), QtGui.QApplication.translate("MainWindow", "Bruteforcer", None, QtGui.QApplication.UnicodeUTF8))
        self.repeaterheaderbody.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">GET / HTTP/1.1</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Accept:*/*</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Cache-Control:no-cache</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.repeaterurledit.setText(QtGui.QApplication.translate("MainWindow", "http://localhost", None, QtGui.QApplication.UnicodeUTF8))
        self.repeaterurledit.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "http(s)://IP:PORT", None, QtGui.QApplication.UnicodeUTF8))
        self.repeatersend.setText(QtGui.QApplication.translate("MainWindow", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.repeatertabs.setTabText(self.repeatertabs.indexOf(self.repeaterreq), QtGui.QApplication.translate("MainWindow", "Request", None, QtGui.QApplication.UnicodeUTF8))
        self.repeatertabs.setTabText(self.repeatertabs.indexOf(self.repeaterres), QtGui.QApplication.translate("MainWindow", "Response", None, QtGui.QApplication.UnicodeUTF8))
        self.repeatertabs.setTabText(self.repeatertabs.indexOf(self.repeatercookies), QtGui.QApplication.translate("MainWindow", "Cookies", None, QtGui.QApplication.UnicodeUTF8))
        self.repeatertabs.setTabText(self.repeatertabs.indexOf(self.repeaterview), QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.repeater), QtGui.QApplication.translate("MainWindow", "Repeater", None, QtGui.QApplication.UnicodeUTF8))
        self.sqliedit.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Sqlmap Command", None, QtGui.QApplication.UnicodeUTF8))
        self.sqlistart.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sqli), QtGui.QApplication.translate("MainWindow", "SQLi", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "URL for XSS injections", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.xss), QtGui.QApplication.translate("MainWindow", "XSS", None, QtGui.QApplication.UnicodeUTF8))
        self.expedit.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Query to be searched in www.exploit-db.com", None, QtGui.QApplication.UnicodeUTF8))
        self.expstart.setText(QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.onlinebot), QtGui.QApplication.translate("MainWindow", "Online Exploits", None, QtGui.QApplication.UnicodeUTF8))
        self.encoderstart.setItemText(0, QtGui.QApplication.translate("MainWindow", "Select a tool - Encoder/Decoder", None, QtGui.QApplication.UnicodeUTF8))
        self.encoderstart.setItemText(1, QtGui.QApplication.translate("MainWindow", "Base-64 Encoder", None, QtGui.QApplication.UnicodeUTF8))
        self.encoderstart.setItemText(2, QtGui.QApplication.translate("MainWindow", "Base-64 Decoder", None, QtGui.QApplication.UnicodeUTF8))
        self.encoderstart.setItemText(3, QtGui.QApplication.translate("MainWindow", "HTML Encoder", None, QtGui.QApplication.UnicodeUTF8))
        self.encoderstart.setItemText(4, QtGui.QApplication.translate("MainWindow", "HTML Decoder", None, QtGui.QApplication.UnicodeUTF8))
        self.encoderstart.setItemText(5, QtGui.QApplication.translate("MainWindow", "MD5 hashing", None, QtGui.QApplication.UnicodeUTF8))
        self.encoderstart.setItemText(6, QtGui.QApplication.translate("MainWindow", "SHA hashing", None, QtGui.QApplication.UnicodeUTF8))
        self.encoderstart.setItemText(7, QtGui.QApplication.translate("MainWindow", "URL Encoder", None, QtGui.QApplication.UnicodeUTF8))
        self.encoderstart.setItemText(8, QtGui.QApplication.translate("MainWindow", "URL Decoder", None, QtGui.QApplication.UnicodeUTF8))
        self.input.setText(QtGui.QApplication.translate("MainWindow", "Input :", None, QtGui.QApplication.UnicodeUTF8))
        self.output.setText(QtGui.QApplication.translate("MainWindow", "Output : ", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.encoder), QtGui.QApplication.translate("MainWindow", "En(De)coder", None, QtGui.QApplication.UnicodeUTF8))
        self.browsergofront.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.browser), QtGui.QApplication.translate("MainWindow", "Browser", None, QtGui.QApplication.UnicodeUTF8))
        self.shellstart.setText(QtGui.QApplication.translate("MainWindow", "Open Terminal", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.shell), QtGui.QApplication.translate("MainWindow", "Shell", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setStatusTip(QtGui.QApplication.translate("MainWindow", "About project", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+L", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setText(QtGui.QApplication.translate("MainWindow", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit_2.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))

import assets_rc
